### ISSUE TITLE
How to use a custom build dir?

### ISSUE THREAD

**Issue by ddahan** [moneymeets/python-poetry-buildpack#33]
My poetry files are not at the root of my project.
So, when I try to deploy the project on Heroku, it fails on the detect phase.

As a workaround, I noticed I can create symbolic links, it works but it's a bit ugly to me.
Is there any other way? I noticed a buildpack works with `BUILD_DIR` var but I did not find where I can specify it.

Thanks.

**Comment by zyv** [comment]
Hi @ddahan ,

`BUILD_DIR` is an internal variable which is part of Buildpack API - it is not possible to set this variable externally. As such our buildpack doesn't support projects located in subdirectories and I think it's also the wrong level to support it in our code.

One could write another buildpack to do that in a generic way. This buildpack seems to do exactly that and has most stars:

https://github.com/negativetwelve/heroku-buildpack-subdir

Alternatively, you can indeed play with symlinks, but I can understand that it looks ugly und feels wrong...

Does this address your question?

**Comment by ddahan** [comment]
Thanks for the fast answer :)
I realized most buildpacks (not only this one) expect stuff to be at root directory. Thus, I decided to put all code at root, rather than messing with symlinks and other exotic buildpacks.

But your the solution you provided seems to be a good idea to try too.

**Comment by zyv** [comment]
> I realized most buildpacks (not only this one) expect stuff to be at root directory. Thus, I decided to put all code at root, rather than messing with symlinks and other exotic buildpacks.

That's correct, if you want to minimise the number of problems you'll run into with the platform, it's best to go with the flow and just put the code at root :-) Otherwise, I think buildpack composition is the best choice.

I'll close this issue for now, good luck with your projects!
