### ISSUE TITLE
Publish to Buildpacks.io

### ISSUE THREAD

**Issue by tomh4** [moneymeets/python-poetry-buildpack#40]
Hello dear @marns93 ,
would you mind publishing the pack to Buildpacks.io?
Here is a quick guide : https://buildpacks.io/docs/buildpack-author-guide/publish-a-buildpack/

**Comment by marns93** [comment]
> Hello dear @marns93 , would you mind publishing the pack to Buildpacks.io? Here is a quick guide : https://buildpacks.io/docs/buildpack-author-guide/publish-a-buildpack/

Hi @tomh4 ,
thanks for your request. At this moment there are no plans to use Buildpacks.io, but I can have a look at it if there is more time for me.

**Comment by tomh4** [comment]
Hello, with your permission I could help, at the end it is just building the pack and raising an issue in their repo, the rest happens automatically

**Comment by zyv** [comment]
Hi @tomh4 - it would be great if you could help. Could you please tell us more how does this work? Do we have to do something every time we update this buildpack, or it's more like a catalog, and we have to publish once, and then just forget about it. If we regularly need to push updates there, this would be too much work for us.

**Comment by tomh4** [comment]
@zyv I forked the repository and made some adjustements, the repo as is, is not compatible with buildpacks. We could make a buildpack-compatible branch or something. I have written a github action that automatically deploys the pack to buildpacks.io
I am not sure what the best way is to maintain both versions, do you need to do changes to the build code often?

**Comment by zyv** [comment]
Apologies for the long silence...


I've had a look at the changes and it looks quite invasive. I have also checked the current state of the registry, and it seems that there are already some maintained CNB buildpacks for Poetry:

https://github.com/paketo-buildpacks?q=poetry

We have no interest in CNB and no capacity to maintain get into it "just for fun", so I would close this issue and recommend using Paketo buildpacks instead.
