### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pywin32==304 (from versions: none)

### ISSUE THREAD

**Issue by dilipvaleti** [moneymeets/python-poetry-buildpack#49]
When we use this build pack in one of our Heroku instance, we got the below error and build rejected.
![image](https://user-images.githubusercontent.com/57723484/192756878-94f9ec27-f0ce-46df-8081-96ef9cf25564.png)
I was happened when we add new package called **requests-negotiate-sspi**
Let me know if this package support need to be added under buildpack.

**Comment by zyv** [comment]
Hi @dilipvaleti,

This is not a bug in our buildpack. All we do is to export the requirements from Poetry and then run `pip` on the exported file. The error you are showing comes from `pip` after our buildpack has already run during the installation step.

Just try this on Ubuntu:

```shell
$ poetry export -f requirements.txt -o requirements.txt
$ pip install -r requirements.txt
```

This will fail in the same way. The README of ` requests-negotiate-sspi`, which you are depending upon says the following:

> This package allows for Single-Sign On HTTP Negotiate authentication using the requests library **on Windows**.

So, this package only works on Windows, and Heroku runs on Ubuntu. You've got no dice...
