### ISSUE TITLE
Add support for exact Python version specification

### ISSUE THREAD

**Issue by rakyi** [moneymeets/python-poetry-buildpack#57]
Hello and thank you for this useful buildpack!

We hit https://github.com/dependabot/dependabot-core/issues/6462 in our project, where Dependabot generates a Python version with the tilde specifier (`~3.11`) in `poetry.lock` when `pyproject.toml` contains a plain full version like `3.11.1`, which is considered invalid with this buildpack.

I saw the discussion in https://github.com/moneymeets/python-poetry-buildpack/issues/6, but would you consider supporting at least the [exact version specifier](https://python-poetry.org/docs/dependency-specification/#exact-requirements) (`==3.11.1`) as suggested in the Dependabot issue discussion? That's what Dependabot generates if it's used in `pyproject.toml`.

**Comment by zyv** [comment]
@rakyi I see no problem with supporting exact version specifier. The easiest implementation I believe would be just to strip `==` at the beginning of the version, add tests and update the documentation. Would you be up for a PR?

**Comment by rakyi** [comment]
OK, I'll take a stab at it.
