### ISSUE TITLE
Pulling from the repository fails

### ISSUE THREAD

**Issue by YanishR** [moneymeets/python-poetry-buildpack#63]
I am trying to use this buildpack for my poetry project but it fails when trying to fetch the custom buildpack:
```
-----> Building on the Heroku-22 stack
-----> Using buildpack: moneymeets/python-poetry-buildpack
 !     error fetching custom buildpack https://buildpack-registry.s3.amazonaws.com/buildpacks/moneymeets/python-poetry-buildpack.tgz
 !     Push failed
```
I am not familiar with heroku or this buildpack.
Would appreciate if someone could point me to a solution please 😺 
I have also reached out to Heroku support

**Comment by zyv** [comment]
So did you follow the instructions for setting up this buildpack? If not, what did you do exactly to add it to your project?

https://github.com/moneymeets/python-poetry-buildpack#how-to-use

**Comment by YanishR** [comment]
I added the buildpack to my project in heroku using the console. I added it and the python heroku buildpack but it always fails with that message, even when it's the only buildpack there.
Why I think this is an issue is because of this message:
```
error fetching custom buildpack https://buildpack-registry.s3.amazonaws.com/buildpacks/moneymeets/python-poetry-buildpack.tgz
```
It should at least be able to fetch the buildpack

**Comment by zyv** [comment]
Which console command did you use to add it, did you use the one from the readme I linked you to?

**Comment by YanishR** [comment]
I didn't use a command but simply added the buildpack under the buildpack section. I will try to do it via the command.

**Comment by zyv** [comment]
> I didn't use a command but simply added the buildpack under the buildpack section. I will try to do it via the command.

Then you must have done it wrong. What did you enter there? It should look as follows:

<img width="1268" alt="Screenshot 2023-07-26 at 11 06 19" src="https://github.com/moneymeets/python-poetry-buildpack/assets/607401/48096c7d-d43a-45d3-8d16-39cc22df4788">

**Comment by YanishR** [comment]
I added it via the CLI and that's solved it! It did look like that, I wonder why it was failing to pull when added through the console. Thank you for the advice 😇
