### ISSUE TITLE
Poetry will not install poetry-plugin-export by default in the future 

### ISSUE THREAD

**Issue by noxan** [moneymeets/python-poetry-buildpack#70]
> Warning: poetry-plugin-export will not be installed by default in a future version of Poetry.
In order to avoid a breaking change and make your automation forward-compatible, please install poetry-plugin-export explicitly. See https://python-poetry.org/docs/plugins/#using-plugins for details on how to install a plugin.
To disable this warning run 'poetry config warnings.export false'.

**Comment by marns93** [comment]
@noxan Thanks for pointing to this.

The plugin will be installed already, see: https://github.com/moneymeets/python-poetry-buildpack/blob/master/bin/compile#L61-L63.
So in my opinion there is nothing to do.

**Comment by noxan** [comment]
Oh I see, thanks for pointing this out @marns93 :)

We could disable the warning with `poetry config warnings.export false` but guess it's not worth the effort - i'll close the issue again.

**Comment by marns93** [comment]
Disabling the warning shouldn't be a big problem.
@felix11h WDYT, should we disable the warning?

**Comment by felix11h** [comment]
@marns93 I also think disabling the warning is ok, but it's also not critical. We can wait for someone to open a pull request for this.
