### ISSUE TITLE
[Announcement] Looking for maintainers

### ISSUE THREAD

**Issue by felix11h** [moneymeets/python-poetry-buildpack#74]
The @moneymeets team has recently moved away from Heroku. Since we are no longer using the buildpack ourselves, we won't be able to add or test new features going forward.

As the buildpack sees decent usage, we are looking for new maintainers for this repository. We can help with setting up a new organization to transfer the repository to, if needed.

Leave a comment if you are interested in maintaining the buildpack. You can also contact @marns93 or me directly, if you have any questions.

Thank you!

**Comment by marns93** [comment]
No need for maintainers because Poetry is now supported in the official buildpack. This repository will be archived in the future.
